config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # Static Pages
  root 'pages#home'
  get '/lecture' => "pages#lecture"
  get '/study'   => "pages#study"

  # Devise routes
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
  	get "/login" => "devise/sessions#new"
  	get "/signup" => "devise/registrations#new"
	end

  # Users resource
	resources :users, only: [:index, :show, :edit, :update, :destroy] do
		get 'lectures', on: :member
    get 'quizzes', on: :member
	end

  # ETC.
	resources :lectures, only: [:create, :destroy]
	resources :enrollments, only: [:create, :destroy]
  resources :quizzes, only: [:index, :create, :destroy]

	delete 'enrollment_path' => "enrollments#destroy"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :omniauthable, :omniauth_providers => [:facebook, :naver]

  validates_presence_of :name

  # Associations
  has_many :enrollments, dependent: :destroy
  has_many :lectures, through: :enrollments
  has_many :quizzes, dependent: :destroy

  # For omniauthable
  def self.from_omniauth(auth)
  	where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    	user.email = auth.info.email
    	user.password = Devise.friendly_token[0,20]
    	user.name = auth.info.name   # assuming the user model has a name
    	user.image = auth.info.image # assuming the user model has an image
    	user.skip_confirmation!
  	end
	end

  # Copy data from sessions whenever a user is initialized before signup
	def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
      if data = session["devise.naver_data"] && session["devise.naver_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def naver
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Naver") if is_navigational_format?
    else
      session["devise.naver_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	layout "user"

	before_action :is_admin, only: [:index]
  before_action :correct_user, only: [:show, :edit, :update]

  # For admin to view all users
  def index
    @users = User.paginate(page: params[:page])
    @user = User.find(current_user.id)
    redirect_to root_url unless current_user.admin?
  end
  
  def show
    @user = User.find(params[:id])

    # temporarily only allow user to view his or her own profile
    if !(current_user == @user)
      redirect_to root_url
    else
      respond_to do |format|
        format.html { redirect_to edit_user_path(@user) }
        format.json { render json: @user }
      end
    end
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_with_password(user_params)
      flash[:success] = "회원정보가 수정 되었습니다!"
      redirect_to @user
    else
      flash[:alert] = "다시 한번 정보를 확인해주십시오."
      redirect_to @user
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  # To display the lectures the user has signed up for (in My Page)
  def lectures
  	@user = User.find(params[:id])
  	@allectures = Lecture.all
  	@lectures = @user.lectures.all
  	@lecture = Lecture.new

  	# when user is not signed in
  	if current_user == nil
  		redirect_to root_url
  	end
  end

  def quizzes
    @user = User.find(params[:id])
    @quizzes = @user.quizzes.all
    @quiz = Quiz.new

    # when user is not signed in
    if current_user == nil
      redirect_to root_url
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :name, 
      :email, 
      :password, 
      :password_confirmation, 
      :current_password
    )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_lecture_create_form.html.erb
<div class="login-box">

  <h2>Create Lecture</h2>

 	<%= form_for(@lecture, url: lectures_path, html: { method: :post }) do |f| %>

   	<div class="field">
     	<%= f.label :subject, "제목" %><br />
     	<%= f.text_field :subject, autofocus: true %>
   	</div>

   	<div class="field">
     	<%= f.label :teacher, "강사" %><br />
     	<%= f.text_field :teacher, autofocus: true %>
   	</div>

   <div class="field">
     <%= f.label :content, "내용" %>
     <%= f.text_area :content, autofocus: true %>
   </div>

   <div class="field">
     <%= f.label :timeinfo, "시간" %><br />
     <%= f.text_field :timeinfo, autofocus: true, placeholder: "YYYY-MM-DD 오전/오후 XX시" %>
   </div>

   <div class="actions">
     <%= f.submit "강의 생성" %>
   </div>

  <% end %>
</div>

app/views/users/_user_edit_form.html.erb
<div class="login-box">
  <h2>회원정보 수정</h2>

  <%= form_for(@user, url: user_path(@user), html: { method: :put }) do |f| %>

    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true %>
    </div>

    <div class="field">
      <%= f.label :name, "이름" %><br />
      <%= f.text_field :name, autofocus: true %>
   </div>

    <% if !(@user.confirmed?) %>
      <div>Currently waiting confirmation for: <%= @user.unconfirmed_email %></div>
    <% end %>

    <div class="field">
      <%= f.label :password, "새 비밀번호" %><br />
      <%= f.password_field :password, autocomplete: "off", placeholder: "수정 할 경우에만 입력" %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation, "새 비밀번호 확인" %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off" %>
    </div>

   <div class="field">
     <%= f.label :current_password, "현재 비밀번호" %><br />
     <%= f.password_field :current_password, autocomplete: "off", placeholder: "수정 확인을 위해 입력" %>
   </div>

    <div class="actions">
     <%= f.submit "회원정보 수정" %>
   </div>
  <% end %>

  <hr>

  <h3>회원탈퇴</h3>

  <p>정말 탈퇴하시겠습니까? <%= button_to "회원탈퇴", registration_path(current_user), data: { confirm: "정말 탈퇴하시겠습니까??" },  method: :delete %></p>

  <%= link_to "뒤로", :back %>
</div>

app/views/users/_user_nav_bar.html.erb
<ul>
	<% if current_user.admin? %>
		<li><%= link_to "회원 리스트", users_path %></li>
	<% end %>
  <li><%= link_to "회원정보 수정", edit_user_path(@user) %></li>
  <li><%= link_to "My Lectures", lectures_user_path(@user) %></li>
  <li><%= link_to "My 언어교환", '#' %></li>
  <li><%= link_to "My 단어장", quizzes_user_path(@user) %></li>
</ul>

app/views/users/edit.html.erb
<% content_for :user_nav do %>
	<%= render 'user_nav_bar' %>
<% end %>

<% content_for :profile_content do %>
	<%= render 'user_edit_form' %>
<% end %>

app/views/users/index.html.erb
<% content_for :user_nav do %>
	<% render 'user_nav_bar.html.erb' %>
<% end %>

<% content_for :profile_content do %>
	<h1>회원 리스트</h1>

	<%= will_paginate %>

	<ul class="users">
  	<% @users.each do |user| %>
    	<li>
      	<% if user.image? %>
          <%= image_tag(user.image, size: 50) %>
        <% else %>
          <%= image_tag("swimming_pool.png", size: 50) %>
        <% end %>
      	<%= link_to user.name, user %>
        <% if current_user.admin? %>
           | <%= link_to "delete", user, method: :delete, data: 
                                { confirm: "You sure?" } %>
        <% end %>
    	</li>
  	<% end %>
	</ul>

	<%= will_paginate %>
<% end %>

app/views/users/lectures.html.erb
<% content_for :user_nav do %>
	<%= render 'user_nav_bar' %>
<% end %>

<% content_for :profile_content do %>
	<ul class="lectures">
		<% if current_user.admin? %>
			<% @allectures.each do |lecture| %>
				<li class="lectures-all">
					<%= lecture.subject %>  |  <%= lecture.timeinfo %>
					  |  <%= link_to "delete", { action: "destroy", controller: "lectures", id: lecture.id }, method: :delete, data: { confirm: "You sure?" } %>
				</li>
			<% end %>
			<%= render 'lecture_create_form' %>
		<% else %>
			<% @lectures.each do |lecture| %>
				<li class="lectures-user">
					<%= lecture.subject %>  |  <%= lecture.timeinfo %>
					 |  <%= link_to "수강 취소", { action: "destroy", controller: "enrollments", user_id: current_user.id, lecture_id: lecture.id }, method: :delete %>
				</li>
			<% end %>
		<%end %>
	</ul>
<% end %>

app/views/users/quizzes.html.erb
<% content_for :user_nav do %>
	<%= render 'user_nav_bar' %>
<% end %>

<% content_for :profile_content do %>
	<ul class="quizzes">
		<% if current_user.admin? || current_user == @user %>
			<% @quizzes.each do |quiz| %>
				<li class="quizzes-index" id=<%= "quiz_#{quiz.id}" %>>
					<%= quiz.word %> 
					      <span class="pull-right">
					      | <%= link_to "x", quiz_path(quiz), method: :delete, data: 
                                { confirm: "정말 삭제 하시겠습니까?" } %>
                                </span>
				</li>
			<% end %>
			<li id="add-quizlet" class="quizzes-index">
				<span id="add-quiz" class="glyphicon glyphicon-plus-sign"></span>
			</li>

			<!-- Modal form: quiz creation -->
			<section id="modal-add-quiz" class="modal fade">
				<div class="modal-body">
					<%= form_for(@quiz, url: quizzes_path, html: {method: :post}, remote: true) do |f| %>

						<div class="quiz-hidden-field">
							<%= f.hidden_field :user_id, :value => @user.id %>
						</div>

						<div class="quiz-word-field">
     					<%= f.label :word, "단어" %><br />
     					<%= f.text_field :word, autofocus: true %>
   					</div>

   					<div class="quiz-definition-field">
     					<%= f.label :definition, "뜻" %><br />
     					<%= f.text_area :definition, autofocus: true %>
   					</div>

   					<div class="actions btn-create-quizlet">
     					<%= f.submit "단어 생성" %>
  					</div>
  				<% end %><!-- form end -->
				</div><!-- Modal body div -->
			</section><!-- Modal section -->
			
			<!-- Prepare modal definition for each quiz -->
			<% @quizzes.each do |quiz| %>
				<section id= <%= "modal-show-quiz-#{quiz.id}-definition" %> class="modal-definition modal fade">
					<div class="modal-body modal-definition-quiz">
						<p><%= quiz.definition %></p>
					</div>
				</section><!-- modal section -->
			<% end %><!-- enum loop end -->
		<% end %>
	</ul>

	<script>
		$(document).ready(function(){
			$("#add-quiz").on('click', function(){
				$("#modal-add-quiz").modal({ show:true });
			});
			<% @quizzes.each do |quiz| %>
				$("<%= "#quiz_#{quiz.id}" %>").on('click', function(){
					$("<%= "#modal-show-quiz-#{quiz.id}-definition" %>").modal({ show:true });
				});
			<% end %>
		});
	</script>
<% end %>

app/views/users/show.html.erb
<h2>users#show</h2>